name: PR Slack Ready for Review

on:
  pull_request:
    types: [ready_for_review]

permissions:
  contents: read

jobs:
  dispatch:
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: ./.github/actions/dispatch-angie-dev-tools
        env:
          GH_TOKEN: ${{ secrets.ANGIE_DEV_TOOLS_BOT_TOKEN }}
        with:
          workflow: pr-ci-slack-ready.yml
