name: PR Slack Ready for Review

on:
  pull_request:
    types: [ready_for_review]

permissions:
  contents: read

jobs:
  notify:
    uses: elementor/angie-dev-tools/.github/workflows/pr-ci-slack-ready.yml@master
    secrets: inherit
